name: Action Practice

on:
  push:
  schedule:
    - cron: '0 * * * *'

env:
  TZ: Asia/Shanghai

jobs:
  # a single job
  a-job-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python3
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip
          pip install datetime requests 
      - name: Run
        env:
          TOKEN: ${{ secrets.TOKEN }}
          AUTH: ${{ secrets.AUTH }}
        run: python3 ./test.py
      - name: Check for changes
        id: check_changes
        run: |
          changes=$(git status --porcelain)
          if [ -z "$changes" ]; then
            echo "No changes. Skipping commit and push."
            echo "SKIP_COMMIT_AND_PUSH=true" >> $GITHUB_ENV 
          else
            echo "There are some changes. Going to commit and push."
            echo "SKIP_COMMIT_AND_PUSH=false" >> $GITHUB_ENV
          fi
      - name: commit
        if: env.SKIP_COMMIT_AND_PUSH != 'true'
        env:
          GIT_NAME: ${{ secrets.GIT_NAME }}
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        run: |
          git config --local user.name $GIT_NAME
          git config --local user.email $GIT_EMAIL
          git add .
          git commit -m "Github action update at `date '+%Y-%m-%d %H:%M:%S'`."
      - name: Push changes
        if: env.SKIP_COMMIT_AND_PUSH != 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GB_TOKEN }}
          branch: main      
